// Python 3.14+ opcode table implementation
// Completely renumbered from 3.13, HAVE_ARGUMENT = 43

#include "opcodes_314.hpp"

namespace pyc {
namespace bytecode {
namespace opcodes {

using op = operand_type;
using F = insn_flag;

const insn_def table_314[] = {
    // No-argument opcodes (0-43)
    {   0, "CACHE",                op::none,       0, F::flag_none, 0 },
    {   1, "BINARY_SLICE",         op::none,      -2, F::flag_none, 0 },
    {   2, "BUILD_TEMPLATE",       op::none,      -1, F::flag_none, 0 },  // f-string templates
    {   3, "BINARY_OP_INPLACE_ADD_UNICODE", op::none, -2, F::flag_none, 0 }, // specialized
    {   4, "CALL_FUNCTION_EX",     op::none,      -3, F::flag_call, 0 },
    {   5, "CHECK_EG_MATCH",       op::none,       0, F::flag_except, 0 },
    {   6, "CHECK_EXC_MATCH",      op::none,      -1, F::flag_except, 0 },
    {   7, "CLEANUP_THROW",        op::none,      -1, F::flag_except, 0 },
    {   8, "DELETE_SUBSCR",        op::none,      -2, F::flag_del, 0 },
    {   9, "END_FOR",              op::none,      -1, F::flag_pop, 0 },
    {  10, "END_SEND",             op::none,      -1, F::flag_pop, 0 },
    {  11, "EXIT_INIT_CHECK",      op::none,      -1, F::flag_none, 0 },
    {  12, "FORMAT_SIMPLE",        op::none,       0, F::flag_none, 0 },
    {  13, "FORMAT_WITH_SPEC",     op::none,      -1, F::flag_none, 0 },
    {  14, "GET_AITER",            op::none,       0, F::flag_none, 0 },
    {  15, "GET_ANEXT",            op::none,       1, F::flag_push, 0 },
    {  16, "GET_ITER",             op::none,       0, F::flag_none, 0 },
    {  17, "RESERVED",             op::none,       0, F::flag_none, 0 },
    {  18, "GET_LEN",              op::none,       1, F::flag_push, 0 },
    {  19, "GET_YIELD_FROM_ITER",  op::none,       0, F::flag_none, 0 },
    {  20, "INTERPRETER_EXIT",     op::none,      -1, F::flag_stop, 0 },
    {  21, "LOAD_BUILD_CLASS",     op::none,       1, F::flag_push, 0 },
    {  22, "LOAD_LOCALS",          op::none,       1, F::flag_push, 0 },
    {  23, "MAKE_FUNCTION",        op::byte,       0, F::flag_none, 0 },
    {  24, "MATCH_KEYS",           op::none,       1, F::flag_push, 0 },
    {  25, "MATCH_MAPPING",        op::none,       1, F::flag_push, 0 },
    {  26, "MATCH_SEQUENCE",       op::none,       1, F::flag_push, 0 },
    {  27, "NOP",                  op::none,       0, F::flag_none, 0 },
    {  28, "NOT_TAKEN",            op::none,       0, F::flag_none, 0 },  // branch hint
    {  29, "POP_EXCEPT",           op::none,      -1, F::flag_pop | F::flag_except, 0 },
    {  30, "POP_ITER",             op::none,      -1, F::flag_pop, 0 },
    {  31, "POP_TOP",              op::none,      -1, F::flag_pop, 0 },
    {  32, "PUSH_EXC_INFO",        op::none,       1, F::flag_push | F::flag_except, 0 },
    {  33, "PUSH_NULL",            op::none,       1, F::flag_push, 0 },
    {  34, "RETURN_GENERATOR",     op::none,       1, F::flag_ret, 0 },
    {  35, "RETURN_VALUE",         op::none,      -1, F::flag_ret | F::flag_stop, 0 },
    {  36, "SETUP_ANNOTATIONS",    op::none,       0, F::flag_none, 0 },
    {  37, "STORE_SLICE",          op::none,      -4, F::flag_store, 0 },
    {  38, "STORE_SUBSCR",         op::none,      -3, F::flag_store | F::flag_cache, 1 },
    {  39, "TO_BOOL",              op::none,       0, F::flag_cache, 3 },
    {  40, "UNARY_INVERT",         op::none,       0, F::flag_none, 0 },
    {  41, "UNARY_NEGATIVE",       op::none,       0, F::flag_none, 0 },
    {  42, "UNARY_NOT",            op::none,       0, F::flag_none, 0 },
    {  43, "WITH_EXCEPT_START",    op::none,       1, F::flag_except, 0 },
    
    // Opcodes with arguments (44+)
    {  44, "BINARY_OP",            op::binop,     -1, F::flag_cache, 1 },
    {  45, "BUILD_INTERPOLATION",  op::byte,       0, F::flag_none, 0 },  // f-string interpolation
    {  46, "BUILD_LIST",           op::byte,       0, F::flag_none, 0 },
    {  47, "BUILD_MAP",            op::byte,       0, F::flag_none, 0 },
    {  48, "BUILD_SET",            op::byte,       0, F::flag_none, 0 },
    {  49, "BUILD_SLICE",          op::byte,       0, F::flag_none, 0 },
    {  50, "BUILD_STRING",         op::byte,       0, F::flag_none, 0 },
    {  51, "BUILD_TUPLE",          op::byte,       0, F::flag_none, 0 },
    {  52, "CALL",                 op::byte,       0, F::flag_call | F::flag_cache, 3 },
    {  53, "CALL_INTRINSIC_1",     op::intrinsic1, 0, F::flag_call, 0 },
    {  54, "CALL_INTRINSIC_2",     op::intrinsic2,-1, F::flag_call, 0 },
    {  55, "CALL_KW",              op::byte,       0, F::flag_call | F::flag_cache, 3 },
    {  56, "COMPARE_OP",           op::compare,   -1, F::flag_cache, 1 },
    {  57, "CONTAINS_OP",          op::byte,      -1, F::flag_cache, 1 },
    {  58, "CONVERT_VALUE",        op::byte,       0, F::flag_none, 0 },
    {  59, "COPY",                 op::byte,       1, F::flag_push, 0 },
    {  60, "COPY_FREE_VARS",       op::byte,       0, F::flag_none, 0 },
    {  61, "DELETE_ATTR",          op::name_idx,  -1, F::flag_del, 0 },
    {  62, "DELETE_DEREF",         op::free_idx,   0, F::flag_del, 0 },
    {  63, "DELETE_FAST",          op::local_idx,  0, F::flag_del, 0 },
    {  64, "DELETE_GLOBAL",        op::name_idx,   0, F::flag_del, 0 },
    {  65, "DELETE_NAME",          op::name_idx,   0, F::flag_del, 0 },
    {  66, "DICT_MERGE",           op::byte,      -1, F::flag_none, 0 },
    {  67, "DICT_UPDATE",          op::byte,      -1, F::flag_none, 0 },
    {  68, "END_ASYNC_FOR",        op::jrel,      -2, F::flag_jump | F::flag_cond | F::flag_except, 0 },
    {  69, "EXTENDED_ARG",         op::byte,       0, F::flag_none, 0 },
    {  70, "FOR_ITER",             op::jrel,       1, F::flag_jump | F::flag_cond | F::flag_cache, 1 },
    {  71, "GET_AWAITABLE",        op::byte,       0, F::flag_none, 0 },
    {  72, "IMPORT_FROM",          op::name_idx,   1, F::flag_push, 0 },
    {  73, "IMPORT_NAME",          op::name_idx,  -1, F::flag_none, 0 },
    {  74, "IS_OP",                op::byte,      -1, F::flag_none, 0 },
    {  75, "JUMP_BACKWARD",        op::jback,      0, F::flag_jump | F::flag_cache, 1 },
    {  76, "JUMP_BACKWARD_NO_INTERRUPT", op::jback, 0, F::flag_jump, 0 },
    {  77, "JUMP_FORWARD",         op::jrel,       0, F::flag_jump, 0 },
    {  78, "LIST_APPEND",          op::byte,      -1, F::flag_none, 0 },
    {  79, "LIST_EXTEND",          op::byte,      -1, F::flag_none, 0 },
    {  80, "LOAD_ATTR",            op::name_idx,   0, F::flag_load | F::flag_cache, 9 },
    {  81, "LOAD_COMMON_CONSTANT", op::common_const, 1, F::flag_load | F::flag_push, 0 },
    {  82, "LOAD_CONST",           op::const_idx,  1, F::flag_load | F::flag_push, 0 },
    {  83, "LOAD_DEREF",           op::free_idx,   1, F::flag_load | F::flag_push, 0 },
    {  84, "LOAD_FAST",            op::local_idx,  1, F::flag_load | F::flag_push, 0 },
    {  85, "LOAD_FAST_AND_CLEAR",  op::local_idx,  1, F::flag_load | F::flag_push, 0 },
    {  86, "LOAD_FAST_BORROW",     op::local_idx,  1, F::flag_load | F::flag_push, 0 },
    {  87, "LOAD_FAST_BORROW_LOAD_FAST_BORROW", op::local_pair, 2, F::flag_load | F::flag_push, 0 },
    {  88, "LOAD_FAST_CHECK",      op::local_idx,  1, F::flag_load | F::flag_push, 0 },
    {  89, "LOAD_FAST_LOAD_FAST",  op::local_pair, 2, F::flag_load | F::flag_push, 0 },
    {  90, "LOAD_FROM_DICT_OR_DEREF", op::free_idx, 0, F::flag_load, 0 },
    {  91, "LOAD_FROM_DICT_OR_GLOBALS", op::name_idx, 0, F::flag_load, 0 },
    {  92, "LOAD_GLOBAL",          op::name_idx,   1, F::flag_load | F::flag_push | F::flag_cache, 4 },
    {  93, "LOAD_NAME",            op::name_idx,   1, F::flag_load | F::flag_push, 0 },
    {  94, "LOAD_SMALL_INT",       op::byte,       1, F::flag_load | F::flag_push, 0 },
    {  95, "LOAD_SPECIAL",         op::byte,       2, F::flag_load, 0 },
    {  96, "LOAD_SUPER_ATTR",      op::name_idx,  -2, F::flag_load | F::flag_cache, 1 },
    {  97, "MAKE_CELL",            op::free_idx,   0, F::flag_none, 0 },
    {  98, "MAP_ADD",              op::byte,      -2, F::flag_none, 0 },
    {  99, "MATCH_CLASS",          op::byte,      -2, F::flag_none, 0 },
    { 100, "POP_JUMP_IF_FALSE",    op::jrel,      -1, F::flag_jump | F::flag_cond | F::flag_cache, 1 },
    { 101, "POP_JUMP_IF_NONE",     op::jrel,      -1, F::flag_jump | F::flag_cond | F::flag_cache, 1 },
    { 102, "POP_JUMP_IF_NOT_NONE", op::jrel,      -1, F::flag_jump | F::flag_cond | F::flag_cache, 1 },
    { 103, "POP_JUMP_IF_TRUE",     op::jrel,      -1, F::flag_jump | F::flag_cond | F::flag_cache, 1 },
    { 104, "RAISE_VARARGS",        op::byte,       0, F::flag_stop, 0 },
    { 105, "RERAISE",              op::byte,      -1, F::flag_stop | F::flag_except, 0 },
    { 106, "SEND",                 op::jrel,       0, F::flag_cache, 1 },
    { 107, "SET_ADD",              op::byte,      -1, F::flag_none, 0 },
    { 108, "SET_FUNCTION_ATTRIBUTE", op::byte,    -1, F::flag_none, 0 },
    { 109, "SET_UPDATE",           op::byte,      -1, F::flag_none, 0 },
    { 110, "STORE_ATTR",           op::name_idx,  -2, F::flag_store | F::flag_cache, 4 },
    { 111, "STORE_DEREF",          op::free_idx,  -1, F::flag_store, 0 },
    { 112, "STORE_FAST",           op::local_idx, -1, F::flag_store, 0 },
    { 113, "STORE_FAST_LOAD_FAST", op::local_pair, 0, F::flag_store | F::flag_load, 0 },
    { 114, "STORE_FAST_STORE_FAST", op::local_pair, -2, F::flag_store, 0 },
    { 115, "STORE_GLOBAL",         op::name_idx,  -1, F::flag_store, 0 },
    { 116, "STORE_NAME",           op::name_idx,  -1, F::flag_store, 0 },
    { 117, "SWAP",                 op::byte,       0, F::flag_none, 0 },
    { 118, "UNPACK_EX",            op::byte,       0, F::flag_none, 0 },
    { 119, "UNPACK_SEQUENCE",      op::byte,       0, F::flag_cache, 1 },
    { 120, "YIELD_VALUE",          op::byte,       0, F::flag_yield, 0 },
    { 128, "RESUME",               op::byte,       0, F::flag_none, 0 },
    
    // Sentinel
    { 0xFF, nullptr, op::none, 0, F::flag_none, 0 }
};

} // namespace opcodes
} // namespace bytecode
} // namespace pyc
