// Python 3.6-3.10 opcode table implementation
// Wordcode format (2 bytes per instruction, no inline caches)

#include "opcodes_36.hpp"

namespace pyc {
namespace bytecode {
namespace opcodes {

using op = operand_type;
using F = insn_flag;

const insn_def table_36_310[] = {
    { 1,   "POP_TOP",              op::none,      -1, F::flag_pop, 0 },
    { 2,   "ROT_TWO",              op::none,       0, F::flag_none, 0 },
    { 3,   "ROT_THREE",            op::none,       0, F::flag_none, 0 },
    { 4,   "DUP_TOP",              op::none,       1, F::flag_push, 0 },
    { 5,   "DUP_TOP_TWO",          op::none,       2, F::flag_push, 0 },
    { 6,   "ROT_FOUR",             op::none,       0, F::flag_none, 0 },
    { 9,   "NOP",                  op::none,       0, F::flag_none, 0 },
    { 10,  "UNARY_POSITIVE",       op::none,       0, F::flag_none, 0 },
    { 11,  "UNARY_NEGATIVE",       op::none,       0, F::flag_none, 0 },
    { 12,  "UNARY_NOT",            op::none,       0, F::flag_none, 0 },
    { 15,  "UNARY_INVERT",         op::none,       0, F::flag_none, 0 },
    { 16,  "BINARY_MATRIX_MULTIPLY",  op::none,   -1, F::flag_none, 0 },
    { 17,  "INPLACE_MATRIX_MULTIPLY", op::none,   -1, F::flag_none, 0 },
    { 19,  "BINARY_POWER",         op::none,      -1, F::flag_none, 0 },
    { 20,  "BINARY_MULTIPLY",      op::none,      -1, F::flag_none, 0 },
    { 22,  "BINARY_MODULO",        op::none,      -1, F::flag_none, 0 },
    { 23,  "BINARY_ADD",           op::none,      -1, F::flag_none, 0 },
    { 24,  "BINARY_SUBTRACT",      op::none,      -1, F::flag_none, 0 },
    { 25,  "BINARY_SUBSCR",        op::none,      -1, F::flag_none, 0 },
    { 26,  "BINARY_FLOOR_DIVIDE",  op::none,      -1, F::flag_none, 0 },
    { 27,  "BINARY_TRUE_DIVIDE",   op::none,      -1, F::flag_none, 0 },
    { 28,  "INPLACE_FLOOR_DIVIDE", op::none,      -1, F::flag_none, 0 },
    { 29,  "INPLACE_TRUE_DIVIDE",  op::none,      -1, F::flag_none, 0 },
    { 48,  "RERAISE",              op::none,      -1, F::flag_stop | F::flag_except, 0 },
    { 49,  "WITH_EXCEPT_START",    op::none,       1, F::flag_except, 0 },
    { 50,  "GET_AITER",            op::none,       0, F::flag_none, 0 },
    { 51,  "GET_ANEXT",            op::none,       1, F::flag_push, 0 },
    { 52,  "BEFORE_ASYNC_WITH",    op::none,       1, F::flag_push, 0 },
    { 54,  "END_ASYNC_FOR",        op::none,      -7, F::flag_except, 0 },
    { 55,  "INPLACE_ADD",          op::none,      -1, F::flag_none, 0 },
    { 56,  "INPLACE_SUBTRACT",     op::none,      -1, F::flag_none, 0 },
    { 57,  "INPLACE_MULTIPLY",     op::none,      -1, F::flag_none, 0 },
    { 59,  "INPLACE_MODULO",       op::none,      -1, F::flag_none, 0 },
    { 60,  "STORE_SUBSCR",         op::none,      -3, F::flag_store, 0 },
    { 61,  "DELETE_SUBSCR",        op::none,      -2, F::flag_del, 0 },
    { 62,  "BINARY_LSHIFT",        op::none,      -1, F::flag_none, 0 },
    { 63,  "BINARY_RSHIFT",        op::none,      -1, F::flag_none, 0 },
    { 64,  "BINARY_AND",           op::none,      -1, F::flag_none, 0 },
    { 65,  "BINARY_XOR",           op::none,      -1, F::flag_none, 0 },
    { 66,  "BINARY_OR",            op::none,      -1, F::flag_none, 0 },
    { 67,  "INPLACE_POWER",        op::none,      -1, F::flag_none, 0 },
    { 68,  "GET_ITER",             op::none,       0, F::flag_none, 0 },
    { 69,  "GET_YIELD_FROM_ITER",  op::none,       0, F::flag_none, 0 },
    { 70,  "PRINT_EXPR",           op::none,      -1, F::flag_pop, 0 },
    { 71,  "LOAD_BUILD_CLASS",     op::none,       1, F::flag_push, 0 },
    { 72,  "YIELD_FROM",           op::none,      -1, F::flag_yield, 0 },
    { 73,  "GET_AWAITABLE",        op::none,       0, F::flag_none, 0 },
    { 74,  "LOAD_ASSERTION_ERROR", op::none,       1, F::flag_push, 0 },
    { 75,  "INPLACE_LSHIFT",       op::none,      -1, F::flag_none, 0 },
    { 76,  "INPLACE_RSHIFT",       op::none,      -1, F::flag_none, 0 },
    { 77,  "INPLACE_AND",          op::none,      -1, F::flag_none, 0 },
    { 78,  "INPLACE_XOR",          op::none,      -1, F::flag_none, 0 },
    { 79,  "INPLACE_OR",           op::none,      -1, F::flag_none, 0 },
    { 82,  "LIST_TO_TUPLE",        op::none,       0, F::flag_none, 0 },
    { 83,  "RETURN_VALUE",         op::none,      -1, F::flag_ret | F::flag_stop, 0 },
    { 84,  "IMPORT_STAR",          op::none,      -1, F::flag_pop, 0 },
    { 85,  "SETUP_ANNOTATIONS",    op::none,       0, F::flag_none, 0 },
    { 86,  "YIELD_VALUE",          op::none,       0, F::flag_yield, 0 },
    { 87,  "POP_BLOCK",            op::none,       0, F::flag_none, 0 },
    { 89,  "POP_EXCEPT",           op::none,      -3, F::flag_pop | F::flag_except, 0 },
    
    // Opcodes with arguments (90+)
    { 90,  "STORE_NAME",           op::name_idx,  -1, F::flag_store, 0 },
    { 91,  "DELETE_NAME",          op::name_idx,   0, F::flag_del, 0 },
    { 92,  "UNPACK_SEQUENCE",      op::byte,       0, F::flag_none, 0 },
    { 93,  "FOR_ITER",             op::jrel,       1, F::flag_jump | F::flag_cond, 0 },
    { 94,  "UNPACK_EX",            op::byte,       0, F::flag_none, 0 },
    { 95,  "STORE_ATTR",           op::name_idx,  -2, F::flag_store, 0 },
    { 96,  "DELETE_ATTR",          op::name_idx,  -1, F::flag_del, 0 },
    { 97,  "STORE_GLOBAL",         op::name_idx,  -1, F::flag_store, 0 },
    { 98,  "DELETE_GLOBAL",        op::name_idx,   0, F::flag_del, 0 },
    { 100, "LOAD_CONST",           op::const_idx,  1, F::flag_load | F::flag_push, 0 },
    { 101, "LOAD_NAME",            op::name_idx,   1, F::flag_load | F::flag_push, 0 },
    { 102, "BUILD_TUPLE",          op::byte,       0, F::flag_none, 0 },
    { 103, "BUILD_LIST",           op::byte,       0, F::flag_none, 0 },
    { 104, "BUILD_SET",            op::byte,       0, F::flag_none, 0 },
    { 105, "BUILD_MAP",            op::byte,       0, F::flag_none, 0 },
    { 106, "LOAD_ATTR",            op::name_idx,   0, F::flag_load, 0 },
    { 107, "COMPARE_OP",           op::compare,   -1, F::flag_none, 0 },
    { 108, "IMPORT_NAME",          op::name_idx,  -1, F::flag_none, 0 },
    { 109, "IMPORT_FROM",          op::name_idx,   1, F::flag_push, 0 },
    { 110, "JUMP_FORWARD",         op::jrel,       0, F::flag_jump, 0 },
    { 111, "JUMP_IF_FALSE_OR_POP", op::jabs,       0, F::flag_jump | F::flag_cond, 0 },
    { 112, "JUMP_IF_TRUE_OR_POP",  op::jabs,       0, F::flag_jump | F::flag_cond, 0 },
    { 113, "JUMP_ABSOLUTE",        op::jabs,       0, F::flag_jump, 0 },
    { 114, "POP_JUMP_IF_FALSE",    op::jabs,      -1, F::flag_jump | F::flag_cond, 0 },
    { 115, "POP_JUMP_IF_TRUE",     op::jabs,      -1, F::flag_jump | F::flag_cond, 0 },
    { 116, "LOAD_GLOBAL",          op::name_idx,   1, F::flag_load | F::flag_push, 0 },
    { 117, "IS_OP",                op::byte,      -1, F::flag_none, 0 },
    { 118, "CONTAINS_OP",          op::byte,      -1, F::flag_none, 0 },
    { 119, "JUMP_IF_NOT_EXC_MATCH",op::jabs,      -2, F::flag_jump | F::flag_cond, 0 },
    { 121, "SETUP_FINALLY",        op::jrel,       0, F::flag_none, 0 },
    { 122, "SETUP_WITH",           op::jrel,       0, F::flag_none, 0 },
    { 124, "LOAD_FAST",            op::local_idx,  1, F::flag_load | F::flag_push, 0 },
    { 125, "STORE_FAST",           op::local_idx, -1, F::flag_store, 0 },
    { 126, "DELETE_FAST",          op::local_idx,  0, F::flag_del, 0 },
    { 130, "RAISE_VARARGS",        op::byte,       0, F::flag_stop, 0 },
    { 131, "CALL_FUNCTION",        op::byte,       0, F::flag_call, 0 },
    { 132, "MAKE_FUNCTION",        op::byte,       0, F::flag_none, 0 },
    { 133, "BUILD_SLICE",          op::byte,       0, F::flag_none, 0 },
    { 135, "LOAD_CLOSURE",         op::free_idx,   1, F::flag_load | F::flag_push, 0 },
    { 136, "LOAD_DEREF",           op::free_idx,   1, F::flag_load | F::flag_push, 0 },
    { 137, "STORE_DEREF",          op::free_idx,  -1, F::flag_store, 0 },
    { 138, "DELETE_DEREF",         op::free_idx,   0, F::flag_del, 0 },
    { 141, "CALL_FUNCTION_KW",     op::byte,       0, F::flag_call, 0 },
    { 142, "CALL_FUNCTION_EX",     op::byte,      -1, F::flag_call, 0 },
    { 143, "SETUP_ASYNC_WITH",     op::jrel,       0, F::flag_none, 0 },
    
    { 144, "EXTENDED_ARG",         op::byte,       0, F::flag_none, 0 },
    
    { 145, "LIST_APPEND",          op::byte,      -1, F::flag_none, 0 },
    { 146, "SET_ADD",              op::byte,      -1, F::flag_none, 0 },
    { 147, "MAP_ADD",              op::byte,      -2, F::flag_none, 0 },
    { 148, "LOAD_CLASSDEREF",      op::free_idx,   1, F::flag_load | F::flag_push, 0 },
    { 154, "SETUP_EXCEPT",         op::jrel,       0, F::flag_none, 0 },
    { 155, "FORMAT_VALUE",         op::byte,       0, F::flag_none, 0 },
    { 156, "BUILD_CONST_KEY_MAP",  op::byte,       0, F::flag_none, 0 },
    { 157, "BUILD_STRING",         op::byte,       0, F::flag_none, 0 },
    { 160, "LOAD_METHOD",          op::name_idx,   1, F::flag_load | F::flag_push, 0 },
    { 161, "CALL_METHOD",          op::byte,       0, F::flag_call, 0 },
    { 162, "LIST_EXTEND",          op::byte,      -1, F::flag_none, 0 },
    { 163, "SET_UPDATE",           op::byte,      -1, F::flag_none, 0 },
    { 164, "DICT_MERGE",           op::byte,      -1, F::flag_none, 0 },
    { 165, "DICT_UPDATE",          op::byte,      -1, F::flag_none, 0 },
    
    // Sentinel
    { 0xFF, nullptr, op::none, 0, F::flag_none, 0 }
};

} // namespace opcodes
} // namespace bytecode
} // namespace pyc
