// Python 2.7 opcode table implementation
// Variable-width instructions (1 byte for no-arg, 3 bytes for arg)

#include "opcodes_27.hpp"

namespace pyc {
namespace bytecode {
namespace opcodes {

using op = operand_type;
using F = insn_flag;

const insn_def table_27[] = {
    { 0,   "STOP_CODE",            op::none,       0, F::flag_stop, 0 },
    { 1,   "POP_TOP",              op::none,      -1, F::flag_pop, 0 },
    { 2,   "ROT_TWO",              op::none,       0, F::flag_none, 0 },
    { 3,   "ROT_THREE",            op::none,       0, F::flag_none, 0 },
    { 4,   "DUP_TOP",              op::none,       1, F::flag_push, 0 },
    { 5,   "ROT_FOUR",             op::none,       0, F::flag_none, 0 },
    { 9,   "NOP",                  op::none,       0, F::flag_none, 0 },
    { 10,  "UNARY_POSITIVE",       op::none,       0, F::flag_none, 0 },
    { 11,  "UNARY_NEGATIVE",       op::none,       0, F::flag_none, 0 },
    { 12,  "UNARY_NOT",            op::none,       0, F::flag_none, 0 },
    { 13,  "UNARY_CONVERT",        op::none,       0, F::flag_none, 0 },
    { 15,  "UNARY_INVERT",         op::none,       0, F::flag_none, 0 },
    { 19,  "BINARY_POWER",         op::none,      -1, F::flag_none, 0 },
    { 20,  "BINARY_MULTIPLY",      op::none,      -1, F::flag_none, 0 },
    { 21,  "BINARY_DIVIDE",        op::none,      -1, F::flag_none, 0 },
    { 22,  "BINARY_MODULO",        op::none,      -1, F::flag_none, 0 },
    { 23,  "BINARY_ADD",           op::none,      -1, F::flag_none, 0 },
    { 24,  "BINARY_SUBTRACT",      op::none,      -1, F::flag_none, 0 },
    { 25,  "BINARY_SUBSCR",        op::none,      -1, F::flag_none, 0 },
    { 26,  "BINARY_FLOOR_DIVIDE",  op::none,      -1, F::flag_none, 0 },
    { 27,  "BINARY_TRUE_DIVIDE",   op::none,      -1, F::flag_none, 0 },
    { 28,  "INPLACE_FLOOR_DIVIDE", op::none,      -1, F::flag_none, 0 },
    { 29,  "INPLACE_TRUE_DIVIDE",  op::none,      -1, F::flag_none, 0 },
    { 30,  "SLICE+0",              op::none,       0, F::flag_none, 0 },
    { 31,  "SLICE+1",              op::none,      -1, F::flag_none, 0 },
    { 32,  "SLICE+2",              op::none,      -1, F::flag_none, 0 },
    { 33,  "SLICE+3",              op::none,      -2, F::flag_none, 0 },
    { 40,  "STORE_SLICE+0",        op::none,      -2, F::flag_store, 0 },
    { 41,  "STORE_SLICE+1",        op::none,      -3, F::flag_store, 0 },
    { 42,  "STORE_SLICE+2",        op::none,      -3, F::flag_store, 0 },
    { 43,  "STORE_SLICE+3",        op::none,      -4, F::flag_store, 0 },
    { 50,  "DELETE_SLICE+0",       op::none,      -1, F::flag_del, 0 },
    { 51,  "DELETE_SLICE+1",       op::none,      -2, F::flag_del, 0 },
    { 52,  "DELETE_SLICE+2",       op::none,      -2, F::flag_del, 0 },
    { 53,  "DELETE_SLICE+3",       op::none,      -3, F::flag_del, 0 },
    { 54,  "STORE_MAP",            op::none,      -2, F::flag_store, 0 },
    { 55,  "INPLACE_ADD",          op::none,      -1, F::flag_none, 0 },
    { 56,  "INPLACE_SUBTRACT",     op::none,      -1, F::flag_none, 0 },
    { 57,  "INPLACE_MULTIPLY",     op::none,      -1, F::flag_none, 0 },
    { 58,  "INPLACE_DIVIDE",       op::none,      -1, F::flag_none, 0 },
    { 59,  "INPLACE_MODULO",       op::none,      -1, F::flag_none, 0 },
    { 60,  "STORE_SUBSCR",         op::none,      -3, F::flag_store, 0 },
    { 61,  "DELETE_SUBSCR",        op::none,      -2, F::flag_del, 0 },
    { 62,  "BINARY_LSHIFT",        op::none,      -1, F::flag_none, 0 },
    { 63,  "BINARY_RSHIFT",        op::none,      -1, F::flag_none, 0 },
    { 64,  "BINARY_AND",           op::none,      -1, F::flag_none, 0 },
    { 65,  "BINARY_XOR",           op::none,      -1, F::flag_none, 0 },
    { 66,  "BINARY_OR",            op::none,      -1, F::flag_none, 0 },
    { 67,  "INPLACE_POWER",        op::none,      -1, F::flag_none, 0 },
    { 68,  "GET_ITER",             op::none,       0, F::flag_none, 0 },
    { 70,  "PRINT_EXPR",           op::none,      -1, F::flag_pop, 0 },
    { 71,  "PRINT_ITEM",           op::none,      -1, F::flag_pop, 0 },
    { 72,  "PRINT_NEWLINE",        op::none,       0, F::flag_none, 0 },
    { 73,  "PRINT_ITEM_TO",        op::none,      -2, F::flag_pop, 0 },
    { 74,  "PRINT_NEWLINE_TO",     op::none,      -1, F::flag_pop, 0 },
    { 75,  "INPLACE_LSHIFT",       op::none,      -1, F::flag_none, 0 },
    { 76,  "INPLACE_RSHIFT",       op::none,      -1, F::flag_none, 0 },
    { 77,  "INPLACE_AND",          op::none,      -1, F::flag_none, 0 },
    { 78,  "INPLACE_XOR",          op::none,      -1, F::flag_none, 0 },
    { 79,  "INPLACE_OR",           op::none,      -1, F::flag_none, 0 },
    { 80,  "BREAK_LOOP",           op::none,       0, F::flag_jump, 0 },
    { 81,  "WITH_CLEANUP",         op::none,      -1, F::flag_except, 0 },
    { 82,  "LOAD_LOCALS",          op::none,       1, F::flag_push, 0 },
    { 83,  "RETURN_VALUE",         op::none,      -1, F::flag_ret | F::flag_stop, 0 },
    { 84,  "IMPORT_STAR",          op::none,      -1, F::flag_pop, 0 },
    { 85,  "EXEC_STMT",            op::none,      -3, F::flag_none, 0 },
    { 86,  "YIELD_VALUE",          op::none,       0, F::flag_yield, 0 },
    { 87,  "POP_BLOCK",            op::none,       0, F::flag_none, 0 },
    { 88,  "END_FINALLY",          op::none,      -3, F::flag_except, 0 },
    { 89,  "BUILD_CLASS",          op::none,      -2, F::flag_none, 0 },
    
    // Opcodes with arguments (90+)
    { 90,  "STORE_NAME",           op::name_idx,  -1, F::flag_store, 0 },
    { 91,  "DELETE_NAME",          op::name_idx,   0, F::flag_del, 0 },
    { 92,  "UNPACK_SEQUENCE",      op::byte,       0, F::flag_none, 0 },
    { 93,  "FOR_ITER",             op::jrel,       1, F::flag_jump | F::flag_cond, 0 },
    { 94,  "LIST_APPEND",          op::byte,      -1, F::flag_none, 0 },
    { 95,  "STORE_ATTR",           op::name_idx,  -2, F::flag_store, 0 },
    { 96,  "DELETE_ATTR",          op::name_idx,  -1, F::flag_del, 0 },
    { 97,  "STORE_GLOBAL",         op::name_idx,  -1, F::flag_store, 0 },
    { 98,  "DELETE_GLOBAL",        op::name_idx,   0, F::flag_del, 0 },
    { 99,  "DUP_TOPX",             op::byte,       0, F::flag_push, 0 },
    { 100, "LOAD_CONST",           op::const_idx,  1, F::flag_load | F::flag_push, 0 },
    { 101, "LOAD_NAME",            op::name_idx,   1, F::flag_load | F::flag_push, 0 },
    { 102, "BUILD_TUPLE",          op::byte,       0, F::flag_none, 0 },
    { 103, "BUILD_LIST",           op::byte,       0, F::flag_none, 0 },
    { 104, "BUILD_SET",            op::byte,       0, F::flag_none, 0 },
    { 105, "BUILD_MAP",            op::byte,       1, F::flag_push, 0 },
    { 106, "LOAD_ATTR",            op::name_idx,   0, F::flag_load, 0 },
    { 107, "COMPARE_OP",           op::compare,   -1, F::flag_none, 0 },
    { 108, "IMPORT_NAME",          op::name_idx,  -1, F::flag_none, 0 },
    { 109, "IMPORT_FROM",          op::name_idx,   1, F::flag_push, 0 },
    { 110, "JUMP_FORWARD",         op::jrel,       0, F::flag_jump, 0 },
    { 111, "JUMP_IF_FALSE_OR_POP", op::jabs,       0, F::flag_jump | F::flag_cond, 0 },
    { 112, "JUMP_IF_TRUE_OR_POP",  op::jabs,       0, F::flag_jump | F::flag_cond, 0 },
    { 113, "JUMP_ABSOLUTE",        op::jabs,       0, F::flag_jump, 0 },
    { 114, "POP_JUMP_IF_FALSE",    op::jabs,      -1, F::flag_jump | F::flag_cond, 0 },
    { 115, "POP_JUMP_IF_TRUE",     op::jabs,      -1, F::flag_jump | F::flag_cond, 0 },
    { 116, "LOAD_GLOBAL",          op::name_idx,   1, F::flag_load | F::flag_push, 0 },
    { 119, "CONTINUE_LOOP",        op::jabs,       0, F::flag_jump, 0 },
    { 120, "SETUP_LOOP",           op::jrel,       0, F::flag_none, 0 },
    { 121, "SETUP_EXCEPT",         op::jrel,       0, F::flag_none, 0 },
    { 122, "SETUP_FINALLY",        op::jrel,       0, F::flag_none, 0 },
    { 124, "LOAD_FAST",            op::local_idx,  1, F::flag_load | F::flag_push, 0 },
    { 125, "STORE_FAST",           op::local_idx, -1, F::flag_store, 0 },
    { 126, "DELETE_FAST",          op::local_idx,  0, F::flag_del, 0 },
    { 130, "RAISE_VARARGS",        op::byte,       0, F::flag_stop, 0 },
    { 131, "CALL_FUNCTION",        op::byte,       0, F::flag_call, 0 },
    { 132, "MAKE_FUNCTION",        op::byte,       0, F::flag_none, 0 },
    { 133, "BUILD_SLICE",          op::byte,       0, F::flag_none, 0 },
    { 134, "MAKE_CLOSURE",         op::byte,       0, F::flag_none, 0 },
    { 135, "LOAD_CLOSURE",         op::free_idx,   1, F::flag_load | F::flag_push, 0 },
    { 136, "LOAD_DEREF",           op::free_idx,   1, F::flag_load | F::flag_push, 0 },
    { 137, "STORE_DEREF",          op::free_idx,  -1, F::flag_store, 0 },
    { 140, "CALL_FUNCTION_VAR",    op::byte,       0, F::flag_call, 0 },
    { 141, "CALL_FUNCTION_KW",     op::byte,       0, F::flag_call, 0 },
    { 142, "CALL_FUNCTION_VAR_KW", op::byte,       0, F::flag_call, 0 },
    { 143, "SETUP_WITH",           op::jrel,       7, F::flag_none, 0 },
    
    { 144, "EXTENDED_ARG",         op::byte,       0, F::flag_none, 0 },
    
    { 145, "SET_ADD",              op::byte,      -1, F::flag_none, 0 },
    { 146, "MAP_ADD",              op::byte,      -2, F::flag_none, 0 },
    
    // Sentinel
    { 0xFF, nullptr, op::none, 0, F::flag_none, 0 }
};

} // namespace opcodes
} // namespace bytecode
} // namespace pyc
